language: node_js

node_js:
    - node

stages:
    - test
    - name: build
      if: branch != master
    - name: deploy
      if: branch = master

jobs:
    include:
        - script: npm run test:ci
        - stage: build
          script: npm run build
        - stage: deploy
          before_script: npm run build
          script: skip
