language: node_js

node_js:
    - node

stages:
    - test
    - build

branches:
    except:
        - /^v\d+\.\d+\.\d+$/

jobs:
    include:
        - script: npm run test:ci
        - stage: build
          script: npm run build
          deploy:
              provider: script
              script: bash scripts/deploy.sh
              on:
                  branch: master
